### ISSUE TITLE
Easily import modules in test/ for pytest, also possiby rename "src"

### ISSUE THREAD

**Issue by loic-ehrhardt** [hugueschips/answerator#7]
Hi,

I am wondering what the best way is for importing our modules in test/ directory, for use with pytest? Adjusting `sys.path` works, but it looks like a hack.

Other question: should we rename `src` directory to `answerator`? Then we can do `import answerator` from python in the root directory. I think this naming convention is used in other projects (e.g. https://github.com/horovod/horovod which also has a `test` directory).

**Comment by hugueschips** [comment]
Good point 👍

**Comment by loic-ehrhardt** [comment]
#8 fixes the second part, thanks!

How would you now do `import answerator` from within `test/` ?

**Comment by loic-ehrhardt** [comment]
Actually works directly now. Perfect :+1:
